name: hashi_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  json_annotation: ^4.9.0
  orm: ^4.4.0

dev_dependencies:
  build: ^2.4.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  runner: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
